// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
///
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl8KdjzQqZRwYRJLLNck-XBVi5mJDi9gg',
    appId: '1:987602943670:web:cef0bac8a54a6e6036f017',
    messagingSenderId: '987602943670',
    projectId: 'srm-food',
    authDomain: 'srm-food.firebaseapp.com',
    storageBucket: 'srm-food.appspot.com',
    measurementId: 'G-D8LSRR4KST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqz2SbmwTWqTKMornsNuy0oHcT9WfQA2s',
    appId: '1:987602943670:android:8ad4e6facbc51bd136f017',
    messagingSenderId: '987602943670',
    projectId: 'srm-food',
    storageBucket: 'srm-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv3IHUd0sFZMWyVX02p5JuPUsx1k5DUHQ',
    appId: '1:987602943670:ios:774ce5782206178c36f017',
    messagingSenderId: '987602943670',
    projectId: 'srm-food',
    storageBucket: 'srm-food.appspot.com',
    iosBundleId: 'com.example.foodWastage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv3IHUd0sFZMWyVX02p5JuPUsx1k5DUHQ',
    appId: '1:987602943670:ios:98471b150ed52e6636f017',
    messagingSenderId: '987602943670',
    projectId: 'srm-food',
    storageBucket: 'srm-food.appspot.com',
    iosBundleId: 'com.example.foodWastage.RunnerTests',
  );
}
